server:
  port: 8081
spring:
  application:
    name: market-app
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: user
    password: password
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yml
  kafka:
    bootstrap-servers: localhost:9092
    topics: market_topic
app:
  client-service-url: localhost:8080
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: cluster
  datasource:
    url: jdbc:mysql://mysql-primary-headless:3306/mydb
    username: user
    password: password
  kafka:
    bootstrap-servers: kafka-headless:9092
    topics: market_topic
    security:
      protocol: SSL
    properties:
      #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
      ssl:
        endpoint:
          identification:
            algorithm:
    ssl:
      trust-store-location: file:/var/kafka/kafka.truststore.jks
      trust-store-password: password
      key-store-location: file:/var/kafka/kafka-0.keystore.jks
      key-store-password: password
      key-password: password
app:
  client-service-url: client-app-service