server:
  port: 8081
spring:
  profiles:
    active: "local"
  application:
    name: market-app
app:
  client-service-url: localhost
---
spring:
  config:
    activate:
      on-profile: cluster
server:
  port: 8080
app:
  client-service-url: client-app-service