server:
  port: 8081
spring:
  application:
    name: market-app
  zipkin:
    base-url: http://localhost:9411/
app:
  client-service-url: localhost:8080
---
app:
  client-service-url: client-app-service
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: cluster
  zipkin:
    base-url: http://zipkin-service:9411/