apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-app
  labels:
    app: market-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-app
  template:
    metadata:
      labels:
        app: market-app
    spec:
      containers:
        - name: market-app
          image: abychkov117/market-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: market-app-configmap
            - secretRef:
                name: market-app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: market-app-service
spec:
  selector:
    app: market-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: market-app-configmap
data:
  DATABASE_URI: mysql-primary-headless
---
apiVersion: v1
kind: Secret
metadata:
  name: market-app-secret
type: kubernetes.io/basic-auth
stringData:
  username: user
  password: password