apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  automountServiceAccountToken: false
  containers: #list of containers that present for build, we can define a default container in the Jenkinsfile
    - name: mixed-agent
      image: abychkov117/jenkins-agent-pod:latest
      command: ["tail", "-f", "/dev/null"] #this or any command that is basically a noop is required, this is so that we don't overwrite the entrypoint of the base container
      imagePullPolicy: Always #use cache or pull image for agent
      resources: #limits the resources build container
        requests:
          memory: "8Gi"
          cpu: "500m"
        limits:
          memory: "8Gi"
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock #use the k8s host docker engine
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock