apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app
  labels:
    app: client-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
        - name: client-app
          image: abychkov117/client-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: client-app-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: client-app-secret
                  key: password
          envFrom:
            - configMapRef:
                name: client-app-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: client-app-service
spec:
  selector:
    app: client-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-app-configmap
data:
  DATABASE_URI: mysql-headless
---
apiVersion: v1
kind: Secret
metadata:
  name: client-app-secret
type: kubernetes.io/basic-auth
stringData:
  username: user
  password: password