pipeline{
    agent {
        kubernetes {
            label 'jenkins-agent' //all your pods will be named with this prefix, followed by a unique id
            idleMinutes 5 //how long the pod will live after no jobs have run on it
            yamlFile './.deploy/jenkins/kubernetes-agent-pod.yml' //path to the pod definition relative to the root of our project
            defaultContainer 'mixed-agent' //define a default container if more than a few stages use it, will default to jnlp container
        }
    }
    environment{
    	dockerhub=credentials('dockerhub')
    }
    stages{
        stage('Build maven'){
            steps{
                echo "=====>Build jar with maven"
                sh "cd ./client && mvn clean package"
            }
        }
        stage('Build docker image'){
            steps{
                echo "=====>Build docker image of Client service"
                sh "cd ./client && docker build -t abychkov117/client-app:latest ."
            }
        }
        stage('Push image to Dockerhub'){
            steps{
                echo "=====>Push docker image to Dockerhub registry"
                sh "echo $dockerhub_PSW | docker login -u $dockerhub_USR --password-stdin"
                sh "docker push abychkov117/client-app:latest"
            }
        }
        stage('Deploy client-app to Kubernetes'){
            steps{
                echo "=====>Deploy service manifest files to Kubernetes"
                sh "cd ./client/.deploy && kubectl apply -f client-app-k8s.yml"
            }
        }
    }
}