server:
  port: 8080
spring:
  application:
    name: client-app
  datasource:
    url: jdbc:mysql://${DATABASE_URI:localhost}:3306/mydb
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # create fulltext search index in elasticsearch
        search:
          backend:
            hosts: localhost:9200
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yml
app:
  market-service-url: localhost:8081