server:
  port: 8080
spring:
  profiles:
    active: "local"
  application:
    name: client-app
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yml
app:
  market-service-url: localhost:8081
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: cluster
  datasource:
    url: jdbc:postgresql://postgresql:5432/testdb
    username: testuser
    password: testpass
    driver-class-name: org.postgresql.Driver
app:
  market-service-url: market-app-service