server:
  port: 8080
spring:
  application:
    name: client-app
  datasource:
    url: jdbc:mysql://${DATABASE_URI:localhost}:3306/mydb
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yml
  kafka:
    bootstrap-servers: localhost:9092
    topics: client_topic
  zipkin:
    base-url: http://localhost:9411/
  cache:
    type: redis
    redis:
      time-to-live: 3600000
  redis:
    host: localhost
    port: 6379
app:
  market-service-url: localhost:8081
---
app:
  market-service-url: market-app-service
spring:
  config:
    activate:
      on-profile: cluster
  kafka:
    bootstrap-servers: kafka-headless:9092
    topics: client_topic
    security:
      protocol: SSL
    properties:
      #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
      ssl:
        endpoint:
          identification:
            algorithm:
    ssl:
      trust-store-location: file:/var/kafka/kafka.truststore.jks
      trust-store-password: password
      key-store-location: file:/var/kafka/kafka-0.keystore.jks
      key-store-password: password
      key-password: password
  zipkin:
    base-url: http://zipkin-service:9411/
  redis:
    host: redis-service
#prometheus:
management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true