server:
  port: 8080
spring:
  application:
    name: client-app
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: user
    password: password
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yml
app:
  market-service-url: localhost:8081
---
spring:
  config:
    activate:
      on-profile: cluster
  datasource:
    url: jdbc:mysql://mysql:3306/mydb
    username: user
    password: password
app:
  market-service-url: market-app-service