server:
  port: 8080
spring:
  application:
    name: client-app
  datasource:
    url: jdbc:mysql://${DATABASE_URI:localhost}:3306/mydb
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yml
  zipkin:
    base-url: http://localhost:9411/
  cache:
    type: redis
    redis:
      time-to-live: 3600000
  redis:
    host: localhost
    port: 6379
app:
  market-service-url: localhost:8081
---
spring:
  config:
    activate:
      on-profile: cluster
  zipkin:
    base-url: http://zipkin-service:9411/
  redis:
    host: redis-service
app:
  market-service-url: market-app-service
#prometheus:
management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true